"""모듈명 셰임 설치 — 계획서 리스크 R1 대응.

Windows 사전빌드 휠은 커널을 이렇게 설치한다:

    flex_gemm_ap   cumesh_vb   o_voxel_vb_ap

그런데 upstream 코드(`inference.py`, `app.py`, `pixal3d/*`)는 이렇게 import 한다:

    flex_gemm      cumesh      o_voxel

upstream 을 수정하지 않는다는 원칙(PLAN.md §6)을 지키면서 이 간극을 메우기 위해,
venv 의 site-packages 에 `<정식이름>.py` 재수출 모듈을 심는다.
sys.path 조작보다 이쪽이 나은 이유는 서브프로세스·워커·CLI 어디서 import 해도
동일하게 동작하고, upstream 파일을 건드리지 않기 때문이다.

이미 정식 이름으로 설치돼 있으면 아무것도 하지 않는다.

사용법:
    python src/shims/install_shims.py          # 필요한 셰임만 설치
    python src/shims/install_shims.py --check  # 판정만, 쓰기 없음
    python src/shims/install_shims.py --remove # 설치했던 셰임 제거
"""

from __future__ import annotations

import argparse
import importlib.util
import site
import sys
from pathlib import Path

for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
    except (AttributeError, OSError):
        pass

# upstream이 import하는 이름 → 휠이 실제로 설치하는 이름 후보
# 순서가 곧 우선순위다. 앞에 있는 것을 먼저 쓴다.
#
# o_voxel 은 두 변형이 있고 내용이 다르다:
#   o_voxel_vb     convert/io/serialize + postprocess + rasterize  <- 이쪽이 필요
#   o_voxel_vb_ap  convert/io/serialize 만. postprocess 가 없다.
#
# upstream inference.py 는 `o_voxel.postprocess.to_glb(...)` 로 GLB 를 만든다.
# _ap 변형을 쓰면 생성은 다 끝난 뒤 마지막 내보내기에서
# AttributeError: module has no attribute 'postprocess' 로 죽는다.
ALIASES: dict[str, list[str]] = {
    "flex_gemm": ["flex_gemm_ap", "flex_gemm_vb"],
    "cumesh": ["cumesh_vb"],
    "o_voxel": ["o_voxel_vb", "o_voxel_vb_ap"],
}

# 셰임이 반드시 노출해야 하는 서브모듈. 없으면 설치가 실패로 판정된다.
REQUIRED_SUBMODULES: dict[str, list[str]] = {
    "o_voxel": ["postprocess"],
}

MARKER = "# generated by src/shims/install_shims.py"

TEMPLATE = '''{marker}
"""`{canonical}` 재수출 셰임.

Windows 사전빌드 휠이 이 커널을 `{actual}` 라는 이름으로 설치하지만,
upstream Pixal3D 는 `{canonical}` 로 import 한다. 이 모듈이 그 간극을 메운다.

이 파일은 자동 생성된다. 직접 수정하지 말고 install_shims.py 를 고칠 것.
"""

import importlib as _importlib
import sys as _sys

import {actual} as _impl

# 서브모듈이 패키지 __init__ 에서 자동 import 되지 않는 경우가 있다.
# upstream 은 `o_voxel.postprocess.to_glb(...)` 처럼 속성으로 접근하므로
# 여기서 미리 불러 붙여둔다. 없으면 생성이 다 끝난 뒤 마지막에 죽는다.
for _name in {submodules!r}:
    try:
        _sub = _importlib.import_module("{actual}." + _name)
        setattr(_impl, _name, _sub)
        _sys.modules["{canonical}." + _name] = _sub
    except ImportError:
        pass

# 구현 모듈 자체를 이 이름으로 등록한다. 단순 `from ... import *` 로는
# `import {canonical}.postprocess` 형태가 동작하지 않는다.
_sys.modules[__name__] = _impl
'''


def _find_site_packages() -> Path:
    """이 인터프리터의 site-packages 를 찾는다."""
    candidates = site.getsitepackages() if hasattr(site, "getsitepackages") else []
    for c in candidates:
        p = Path(c)
        if p.name == "site-packages" and p.is_dir():
            return p
    # venv 가 아닌 경우 등 폴백
    import sysconfig

    purelib = sysconfig.get_paths().get("purelib")
    if purelib:
        return Path(purelib)
    raise RuntimeError("site-packages 를 찾지 못했습니다.")


def _module_available(name: str) -> bool:
    """실제로 import 가능한지. find_spec 은 셰임 파일도 잡으므로 존재 확인용."""
    try:
        return importlib.util.find_spec(name) is not None
    except (ImportError, ValueError):
        return False


def _is_our_shim(path: Path) -> bool:
    if not path.is_file():
        return False
    try:
        return MARKER in path.read_text(encoding="utf-8")[:400]
    except OSError:
        return False


def main() -> int:
    ap = argparse.ArgumentParser(description="upstream 모듈명 셰임 설치")
    ap.add_argument("--check", action="store_true", help="판정만 하고 쓰지 않는다")
    ap.add_argument("--remove", action="store_true", help="설치했던 셰임을 제거한다")
    args = ap.parse_args()

    sp = _find_site_packages()
    print(f"  site-packages: {sp}")

    installed, skipped, missing = [], [], []

    for canonical, actuals in ALIASES.items():
        shim_path = sp / f"{canonical}.py"

        if args.remove:
            if _is_our_shim(shim_path):
                shim_path.unlink()
                print(f"  [제거] {canonical}.py")
            continue

        # 이미 정식 이름으로 설치된 진짜 패키지가 있으면 건드리지 않는다
        if _module_available(canonical) and not _is_our_shim(shim_path):
            skipped.append(canonical)
            print(f"  [ OK ] {canonical} — 정식 이름으로 이미 설치됨, 셰임 불필요")
            continue

        actual = next((a for a in actuals if _module_available(a)), None)
        if actual is None:
            missing.append(canonical)
            print(f"  [FAIL] {canonical} — {' / '.join(actuals)} 중 어느 것도 없음")
            continue

        if args.check:
            print(f"  [필요] {canonical}.py  ->  {actual}")
            installed.append(canonical)
            continue

        shim_path.write_text(
            TEMPLATE.format(
                marker=MARKER, canonical=canonical, actual=actual,
                submodules=REQUIRED_SUBMODULES.get(canonical, []),
            ),
            encoding="utf-8",
        )
        installed.append(canonical)
        print(f"  [설치] {canonical}.py  ->  {actual}")

    if args.remove:
        return 0

    # 셰임이 실제로 동작하는지 확인 — 새 인터프리터에서 import 해봐야 정확하다
    if installed and not args.check:
        import subprocess

        # import 만으로는 부족하다. upstream 이 실제로 쓰는 서브모듈까지
        # 접근되는지 봐야 한다 (o_voxel.postprocess.to_glb 등).
        checks = []
        for n in installed:
            checks.append(f"import {n}")
            for sub in REQUIRED_SUBMODULES.get(n, []):
                checks.append(f"assert hasattr({n}, {sub!r}), '{n}.{sub} 없음'")
        probe = subprocess.run(
            [sys.executable, "-c", "; ".join(checks) + "; print('shim-ok')"],
            capture_output=True, text=True,
        )
        if "shim-ok" in probe.stdout:
            print(f"  [ OK ] 셰임 {len(installed)}개 동작 확인")
        else:
            print(f"  [FAIL] 셰임 import 실패:\n{probe.stderr.strip()}")
            return 1

    if missing:
        print()
        print(f"  커널 {len(missing)}개가 설치되지 않았습니다: {', '.join(missing)}")
        print("  setup/03_cuda_wheels.ps1 을 먼저 실행하세요.")
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
